// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mungesat_shkolla.Data;

#nullable disable

namespace Mungesat_shkolla.Migrations
{
    [DbContext(typeof(MungesatDbContext))]
    [Migration("20240627150725_migrimi i ri")]
    partial class migrimiiri
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mungesat_shkolla.Models.KlasaLenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Dita")
                        .HasColumnType("int");

                    b.Property<int>("KlasatId")
                        .HasColumnType("int");

                    b.Property<int>("LendaId")
                        .HasColumnType("int");

                    b.Property<int>("Ora")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KlasatId");

                    b.HasIndex("LendaId");

                    b.ToTable("klasaLenda");
                });

            modelBuilder.Entity("Mungesat_shkolla.Models.Klasat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Emri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KujdestariId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KujdestariId")
                        .IsUnique();

                    b.ToTable("Klasat");
                });

            modelBuilder.Entity("Mungesat_shkolla.Models.Kujdestari", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Emri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mbiemri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("kujdestari");
                });

            modelBuilder.Entity("Mungesat_shkolla.Models.Lenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Emri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Viti")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("lenda");
                });

            modelBuilder.Entity("Mungesat_shkolla.Models.Mungesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Arsyeja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int>("NxenesiId")
                        .HasColumnType("int");

                    b.Property<string>("Oret")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NxenesiId");

                    b.ToTable("mungesa");
                });

            modelBuilder.Entity("Mungesat_shkolla.Models.Nxenesi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Ditelindja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Emri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gjinia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KlasatId")
                        .HasColumnType("int");

                    b.Property<string>("Mbiemri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prindi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KlasatId");

                    b.ToTable("nxenesi");
                });

            modelBuilder.Entity("Mungesat_shkolla.Models.KlasaLenda", b =>
                {
                    b.HasOne("Mungesat_shkolla.Models.Klasat", "Klasat")
                        .WithMany("KlasaLenda")
                        .HasForeignKey("KlasatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mungesat_shkolla.Models.Lenda", "Lenda")
                        .WithMany("KlasaLenda")
                        .HasForeignKey("LendaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Klasat");

                    b.Navigation("Lenda");
                });

            modelBuilder.Entity("Mungesat_shkolla.Models.Klasat", b =>
                {
                    b.HasOne("Mungesat_shkolla.Models.Kujdestari", "Kujdestari")
                        .WithOne("Klasat")
                        .HasForeignKey("Mungesat_shkolla.Models.Klasat", "KujdestariId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kujdestari");
                });

            modelBuilder.Entity("Mungesat_shkolla.Models.Mungesa", b =>
                {
                    b.HasOne("Mungesat_shkolla.Models.Nxenesi", "Nxenesi")
                        .WithMany("MungesaList")
                        .HasForeignKey("NxenesiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nxenesi");
                });

            modelBuilder.Entity("Mungesat_shkolla.Models.Nxenesi", b =>
                {
                    b.HasOne("Mungesat_shkolla.Models.Klasat", "Klasat")
                        .WithMany("Nxenesit")
                        .HasForeignKey("KlasatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Klasat");
                });

            modelBuilder.Entity("Mungesat_shkolla.Models.Klasat", b =>
                {
                    b.Navigation("KlasaLenda");

                    b.Navigation("Nxenesit");
                });

            modelBuilder.Entity("Mungesat_shkolla.Models.Kujdestari", b =>
                {
                    b.Navigation("Klasat")
                        .IsRequired();
                });

            modelBuilder.Entity("Mungesat_shkolla.Models.Lenda", b =>
                {
                    b.Navigation("KlasaLenda");
                });

            modelBuilder.Entity("Mungesat_shkolla.Models.Nxenesi", b =>
                {
                    b.Navigation("MungesaList");
                });
#pragma warning restore 612, 618
        }
    }
}
